export interface Course {
    "id": string,
    "name": string,
    "section": string,
    "descriptionHeading": string,
    "description": string,
    "room": string,
    "ownerId": string,
    "creationTime": string,
    "updateTime": string,
    "enrollmentCode": string,
    "courseState": any,
    "alternateLink": string,
    "teacherGroupEmail": string,
    "courseGroupEmail": string,
    "teacherFolder": any,
    "courseMaterialSets": any[],
    "guardiansEnabled": boolean,
    "calendarId": string
}